name: PR
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize, ready_for_review]

jobs:
  check-pr:
    name: Validate Release Metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jefflinse/pr-semver-bump@v1
        name: Validate PR Metadata
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          require-release-notes: true
          release-notes-prefix: '^### Summary\s*$'
          with-v: true
